name: catkin_make_isolated

on: [push]

jobs:
  build-16-kinetic:
    runs-on: [ubuntu-16.04]
    strategy:
      fail-fast: false
      matrix:
        build_type: ["-DCMAKE_BUILD_TYPE=Debug", "-DCMAKE_BUILD_TYPE=Release"]
        compiler: ["-DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++"]
    steps:
    - name: remove-too-new-boost-not-compatible-with-actionlib
      shell: bash
      run: |
        sudo rm -fr /usr/local/share/boost/1.69.0
    - uses: actions/checkout@v1
      with:
        path: ws/src/csapex/src/csapex_plugins
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: clone_dependencies
      run: |
        cd ..
        echo "Branch: ${{ steps.extract_branch.outputs.branch }}"
        git clone https://github.com/betwo/csapex --branch ${{ steps.extract_branch.outputs.branch }}|| git clone https://github.com/betwo/csapex
        git clone https://github.com/cogsys-tuebingen/cslibs_vision
        git clone https://github.com/cogsys-tuebingen/cslibs_laser_processing
        git clone https://github.com/cogsys-tuebingen/cslibs_arff
        git clone https://github.com/cogsys-tuebingen/cslibs_indexed_storage
    - uses: betwo/github-setup-catkin@v1.0.0
      with:
        ros-version: 'kinetic'
        workspace: $HOME/work/csapex_core_plugins/ws
    - name: install_compiler
      run: |
        sudo add-apt-repository ppa:jonathonf/gcc-7.1
        sudo apt-get update
        sudo apt-get install -y gcc-7 g++-7
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 50 --slave /usr/bin/g++ g++ /usr/bin/g++-7
        sudo update-alternatives --set gcc "/usr/bin/gcc-7"
    - name: build
      run: |
        cd $HOME/work/csapex_core_plugins/ws
        catkin_make_isolated ${{ matrix.build_type }} ${{ matrix.compiler }}
    

  build-18-melodic:
    runs-on: [ubuntu-18.04]
    strategy:
      fail-fast: false
      matrix:
        build_type: ["-DCMAKE_BUILD_TYPE=Debug", "-DCMAKE_BUILD_TYPE=Release"]
        compiler: ["-DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++", "-DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++"]
    steps:
    - uses: actions/checkout@v1
      with:
        path: ws/src/csapex/src/csapex_plugins
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: clone_dependencies
      run: |
        cd ..
        git clone https://github.com/betwo/csapex --branch ${{ steps.extract_branch.outputs.branch }} || git clone https://github.com/betwo/csapex
        git clone https://github.com/cogsys-tuebingen/cslibs_vision
        git clone https://github.com/cogsys-tuebingen/cslibs_laser_processing
        git clone https://github.com/cogsys-tuebingen/cslibs_arff
        git clone https://github.com/cogsys-tuebingen/cslibs_indexed_storage
    - uses: betwo/github-setup-catkin@v1.0.0
      with:
        ros-version: 'melodic'
        workspace: $HOME/work/csapex_core_plugins/ws
    - name: install_compiler
      run: sudo apt-get install -y gcc clang
    - name: build
      run: |
        cd $HOME/work/csapex_core_plugins/ws
        catkin_make_isolated ${{ matrix.build_type }} ${{ matrix.compiler }}
